### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by TkTech**
Don't commit just yet. Works, but doesn't generate a MOBI.

### CODE REVIEW

**Comment by TkTech** [comment]
@Antrikshy Well, this is done. Just missing an updated README.md and automatically converting the .html to .mobi with kindlegen. Tested the results on a couple of kindles, looks good (IMO).

**Comment by Antrikshy** [comment]
I actually did regret using the odd casing in the name and the command after I released it. It should have been r2k. But is it a good idea to change it now? Won't that mess up PyPI and everyone who is using it?

**Comment by TkTech** [comment]
@Antrikshy So far as I am aware, PyPi is not case sensitive for uploaded packages. It will just redirect to the most recent casing.

ex: https://pypi.python.org/pypi/reddit2kindle -> https://pypi.python.org/pypi/reddit2Kindle

**Comment by Antrikshy** [comment]
I realized this after the merge, but `cli.py` isn't working for me. I get `ImportError: No module named r2klib` on the line `env = Environment(loader=PackageLoader('r2klib', 'templates'))`.

**Comment by TkTech** [comment]
@Antrikshy working fine. How did you try to install and use it?

**Comment by Antrikshy** [comment]
I just realized that I may have done it wrong. I used the cli.py file directly. It should work fine when installed, correct? I reverted the changes, but I can bring them back.

**Comment by TkTech** [comment]
You can use it directly if your PYTHONPATH is set to the parent directory (so that it knows how to find r2klib) or you can install it (try `python setup.py develop`, which will install it in a way that any changes you make are reflected immediately).

**Comment by Antrikshy** [comment]
I see. I am very grateful for all the help! You cleaned up my code beyond recognition. While I will give you credit everywhere, I feel like you own the entire thing.

**Comment by TkTech** [comment]
@Antrikshy Just took your (neat!) idea and cleaned it up a bit :) It should be clean and easy to extend now - for example, here's how you add support for "hot" posts -https://github.com/TkTech/reddit2Kindle/commit/0994ef729dd7f56c2eebac02d8a549a72d4a8741

**Comment by TkTech** [comment]
@Antrikshy Is there anything else you need for this? I can't send you another PR for hot/top since Github sees that all of the commits have already been merged.

**Comment by Antrikshy** [comment]
No. I'll manage from here. I had to wrestle a bit with Git and did some ghetto merging, so if you notice something out of place, don't mind it. I have decided to actually sit down and learn the ins and outs of Git soon.

**Comment by TkTech** [comment]
It's well worth the investment :) Can be a royal pain tho'.

**Pull request merged**
